{% set name = "codespell" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 360c7d10f75e65f67bad720af7007e1060a5d395670ec11a7ed1fed9dd17471f

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - codespell = codespell_lib:_script_main

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  commands:
    - codespell --version

about:
  home: https://github.com/codespell-project/codespell
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  summary: Fix common misspellings in text files, usually source code.

  description: |
    Fix common misspellings in text files. It's designed primarily for
    checking misspelled words in source code, but it can be used with
    other files as well.
  dev_url: https://github.com/codespell-project/codespell

extra:
  recipe-maintainers:
    - dopplershift
    - larsoner
