{% set name = "codespell" %}
{% set version = "1.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e0ecaa51e2965a1dfdc0ea53a6299d9f1840fca155f337ab1b6ec6dd0ae07887

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - codespell = codespell_lib:_script_main

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  commands:
    - codespell --version

about:
  home: https://github.com/codespell-project/codespell
  license: GPL-2.0
  license_family: GPL
  license_file: COPYING
  summary: Fix common misspellings in text files, usually source code.

  description: |
    Fix common misspellings in text files. It's designed primarily for
    checking misspelled words in source code, but it can be used with
    other files as well.
  dev_url: https://github.com/codespell-project/codespell

extra:
  recipe-maintainers:
    - dopplershift
